import Footer from "@/components/footer/Footer";
import NavBar from "@/components/nav/Navbar";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Image as ImageIcon, Wand2, BrainCircuit, Split } from "lucide-react";
import type { ReactNode } from "react";

function FeaturesPage() {
  return (
    <>
      <NavBar />

      <section className="bg-zinc-50 py-16 md:py-32 dark:bg-transparent">
        <div className="@container mx-auto max-w-5xl px-6">
          <div className="text-center">
            <h2 className="text-balance text-4xl font-semibold lg:text-5xl">
              Built to Empower Your Creativity
            </h2>
            <p className="mt-4">
              Morphix unites powerful AI tools to help you create, edit, and explore.
            </p>
          </div>

          <div className="@min-4xl:max-w-full @min-4xl:grid-cols-3 mx-auto mt-8 grid max-w-sm gap-6 *:text-center md:mt-16">
            {/* Generate Images */}
            <Card className="group shadow-zinc-950/5">
              <CardHeader className="pb-3">
                <CardDecorator>
                  <ImageIcon className="size-6" aria-hidden />
                </CardDecorator>
                <h3 className="mt-6 font-medium">Generate Stunning Images</h3>
              </CardHeader>
              <CardContent>
                <p className="text-sm">
                  Instantly transform prompts into breathtaking visuals with
                  multiple AI models in one place.
                </p>
              </CardContent>
            </Card>

            {/* Customization & Editing */}
            <Card className="group shadow-zinc-950/5">
              <CardHeader className="pb-3">
                <CardDecorator>
                  <Wand2 className="size-6" aria-hidden />
                </CardDecorator>
                <h3 className="mt-6 font-medium">Refine & Customize</h3>
              </CardHeader>
              <CardContent>
                <p className="mt-3 text-sm">
                  Edit images with filters, color grading, and prompt-based
                  modifications to get the perfect output.
                </p>
              </CardContent>
            </Card>

            {/* AI Inspiration */}
            <Card className="group shadow-zinc-950/5">
              <CardHeader className="pb-3">
                <CardDecorator>
                  <BrainCircuit className="size-6" aria-hidden />
                </CardDecorator>
                <h3 className="mt-6 font-medium">AI-Powered Inspiration</h3>
              </CardHeader>
              <CardContent>
                <p className="mt-3 text-sm">
                  Discover new ideas with AI-assisted suggestions that push your
                  creativity beyond limits.
                </p>
              </CardContent>
            </Card>

            {/* Compare Results */}
            <Card className="group shadow-zinc-950/5">
              <CardHeader className="pb-3">
                <CardDecorator>
                  <Split className="size-6" aria-hidden />
                </CardDecorator>
                <h3 className="mt-6 font-medium">Compare Results</h3>
              </CardHeader>
              <CardContent>
                <p className="mt-3 text-sm">
                  Easily compare images generated by multiple models side by
                  side and choose your favorite.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}

export default FeaturesPage;

const CardDecorator = ({ children }: { children: ReactNode }) => (
  <div className="relative mx-auto size-36 duration-200 [--color-border:color-mix(in_oklab,var(--color-zinc-950)10%,transparent)] group-hover:[--color-border:color-mix(in_oklab,var(--color-zinc-950)20%,transparent)] dark:[--color-border:color-mix(in_oklab,var(--color-white)15%,transparent)] dark:group-hover:bg-white/5 dark:group-hover:[--color-border:color-mix(in_oklab,var(--color-white)20%,transparent)]">
    <div
      aria-hidden
      className="absolute inset-0 bg-[linear-gradient(to_right,var(--color-border)_1px,transparent_1px),linear-gradient(to_bottom,var(--color-border)_1px,transparent_1px)] bg-[size:24px_24px]"
    />
    <div
      aria-hidden
      className="bg-radial to-background absolute inset-0 from-transparent to-75%"
    />
    <div className="bg-background absolute inset-0 m-auto flex size-12 items-center justify-center border-l border-t">
      {children}
    </div>
  </div>
);
